/**
 * ⚠️ AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY.
 * Source of Truth: book-sources/term-1/05-canonical-data/
 * Generated by: scripts/build-all-data.mjs (Deterministic Reproducible Build)
 */

import { DeepChallengingQuestion } from "../types";
import { LESSON_1_1_DEEP_QUESTIONS } from "./lesson-1-1";
import { LESSON_1_2_DEEP_QUESTIONS } from "./lesson-1-2";
import { LESSON_1_3_DEEP_QUESTIONS } from "./lesson-1-3";
import { LESSON_1_4_DEEP_QUESTIONS } from "./lesson-1-4";

export * from "./lesson-1-1";
export * from "./lesson-1-2";
export * from "./lesson-1-3";
export * from "./lesson-1-4";

export const CHAPTER_1_DEEP_QUESTIONS: Record<string, DeepChallengingQuestion[]> = {
  "1-1": LESSON_1_1_DEEP_QUESTIONS,
  "1-2": LESSON_1_2_DEEP_QUESTIONS,
  "1-3": LESSON_1_3_DEEP_QUESTIONS,
  "1-4": LESSON_1_4_DEEP_QUESTIONS,
};
