/**
 * ⚠️ AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY.
 * Source of Truth: book-sources/term-1/05-canonical-data/
 * Generated by: scripts/build-all-data.mjs (Deterministic Reproducible Build)
 */

import { DeepChallengingQuestion } from "../types";
import { LESSON_3_1_DEEP_QUESTIONS } from "./lesson-3-1";
import { LESSON_3_2_DEEP_QUESTIONS } from "./lesson-3-2";
import { LESSON_3_3_DEEP_QUESTIONS } from "./lesson-3-3";

export * from "./lesson-3-1";
export * from "./lesson-3-2";
export * from "./lesson-3-3";

export const CHAPTER_3_DEEP_QUESTIONS: Record<string, DeepChallengingQuestion[]> = {
  "3-1": LESSON_3_1_DEEP_QUESTIONS,
  "3-2": LESSON_3_2_DEEP_QUESTIONS,
  "3-3": LESSON_3_3_DEEP_QUESTIONS,
};
