/**
 * ⚠️ AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY.
 * Source of Truth: book-sources/term-1/05-canonical-data/
 * Generated by: scripts/build-all-data.mjs (Deterministic Reproducible Build)
 */

import { DeepChallengingQuestion } from "../types";
import { LESSON_4_1_DEEP_QUESTIONS } from "./lesson-4-1";
import { LESSON_4_2_DEEP_QUESTIONS } from "./lesson-4-2";
import { LESSON_4_3_DEEP_QUESTIONS } from "./lesson-4-3";
import { LESSON_4_4_DEEP_QUESTIONS } from "./lesson-4-4";

export * from "./lesson-4-1";
export * from "./lesson-4-2";
export * from "./lesson-4-3";
export * from "./lesson-4-4";

export const CHAPTER_4_DEEP_QUESTIONS: Record<string, DeepChallengingQuestion[]> = {
  "4-1": LESSON_4_1_DEEP_QUESTIONS,
  "4-2": LESSON_4_2_DEEP_QUESTIONS,
  "4-3": LESSON_4_3_DEEP_QUESTIONS,
  "4-4": LESSON_4_4_DEEP_QUESTIONS,
};
