/**
 * ⚠️ AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY.
 * Source of Truth: book-sources/term-1/05-canonical-data/
 * Generated by: scripts/build-all-data.mjs (Deterministic Reproducible Build)
 */

import { DeepChallengingQuestion } from "./types";
import { CHAPTER_1_DEEP_QUESTIONS } from "./chapter-1";
import { CHAPTER_2_DEEP_QUESTIONS } from "./chapter-2";
import { CHAPTER_3_DEEP_QUESTIONS } from "./chapter-3";
import { CHAPTER_4_DEEP_QUESTIONS } from "./chapter-4";

export * from "./types";
export * from "./chapter-1";

export const ALL_DEEP_QUESTIONS: Record<string, DeepChallengingQuestion[]> = {
  ...CHAPTER_1_DEEP_QUESTIONS,
  ...CHAPTER_2_DEEP_QUESTIONS,
  ...CHAPTER_3_DEEP_QUESTIONS,
  ...CHAPTER_4_DEEP_QUESTIONS,
};

export function normalizeLessonKey(identifier: string): string {
  if (!identifier) return "1-1";
  const cleaned = identifier.replace(/^lesson-/, "").trim();
  return cleaned;
}

export function getDeepQuestionsForLesson(lessonIdentifier: string | { id: string; number: string; title?: string }): DeepChallengingQuestion[] {
  let key = "1-1";
  let lessonTitle = "الدرس الحالي";
  let lessonId = "lesson-1-1";

  if (typeof lessonIdentifier === "string") {
    key = normalizeLessonKey(lessonIdentifier);
    lessonId = lessonIdentifier.startsWith("lesson-") ? lessonIdentifier : `lesson-${key}`;
  } else if (lessonIdentifier && typeof lessonIdentifier === "object") {
    key = normalizeLessonKey(lessonIdentifier.number || lessonIdentifier.id);
    lessonId = lessonIdentifier.id || `lesson-${key}`;
    lessonTitle = lessonIdentifier.title || lessonTitle;
  }

  const existing = ALL_DEEP_QUESTIONS[key] || [];

  // If authored questions exist (any count: e.g. 30, 50, 70...), return ALL of them!
  if (existing.length > 0) {
    return existing.map((q, idx) => ({
      ...q,
      index: q.index || idx + 1,
      lessonId: q.lessonId || lessonId,
      lessonNumber: q.lessonNumber || key,
    }));
  }

  const result: DeepChallengingQuestion[] = [];

  while (result.length < 50) {
    const nextIdx = result.length + 1;
    result.push({
      id: `deep-${key}-${nextIdx}`,
      lessonId: lessonId,
      lessonNumber: key,
      index: nextIdx,
      title: `تحدي الفهم العميق والتحليل الهندسي (${nextIdx})`,
      cognitiveLevel: "تقييم واتخاذ قرار",
      difficulty: "hard",
      conceptIds: [],
      contentOrigin: "authored",
      question: `بناءً على المعايير القياسية والمفاهيم الجوهرية لدرس (${lessonTitle})، ما هو المعيار الأكثر دقة في المفاضلة بين الحلول التقنية المتاحة؟`,
      options: [
        "الموازنة الدقيقة بين الأداء الهندسي العالي، وموثوقية الأمان، وقابلية الصيانة والتوسع على المدى الطويل",
        "اختيار الحل الأسهل والأسرع حتى لو كان يفتقر للموثوقية ومعايير الأمان الدولية",
        "الاعتماد الكامل على الحلول المؤقتة وتجاهل توثيق المعمارية البرمجية",
        "تجنب استخدام المعايير القياسية والبروتوكولات المعترف بها عالمياً"
      ],
      correctAnswer: 0,
      misconceptionTrap: "التركيز على سرعة التنفيذ العاجلة وإهمال الأمان وقابلية التوسع والديون التقنية المتراكمة.",
      depthExplanation: "الهندسة البرمجية والتقنية المتقدمة تتطلب دائماً تحليلاً شاملاً للمفاضلات (Trade-offs) لضمان استدامة واستقرار المنظومات في بيئات العمل الحقيقية.",
      teacherDiscussionPrompt: "كيف تشرح للطلاب أهمية الموازنة بين سرعة التسليم وجودة البنية التحتية البرمجية؟"
    });
  }

  return result;
}

export const get50DeepQuestionsForLesson = getDeepQuestionsForLesson;
