/**
 * ⚠️ AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY.
 * Source of Truth: book-sources/term-1/05-canonical-data/
 * Generated by: scripts/build-all-data.mjs (Deterministic Reproducible Build)
 */

import { DeepChallengingQuestion } from "../types";
import { LESSON_2_1_DEEP_QUESTIONS } from "./lesson-2-1";
import { LESSON_2_2_DEEP_QUESTIONS } from "./lesson-2-2";
import { LESSON_2_3_DEEP_QUESTIONS } from "./lesson-2-3";

export * from "./lesson-2-1";
export * from "./lesson-2-2";
export * from "./lesson-2-3";

export const CHAPTER_2_DEEP_QUESTIONS: Record<string, DeepChallengingQuestion[]> = {
  "2-1": LESSON_2_1_DEEP_QUESTIONS,
  "2-2": LESSON_2_2_DEEP_QUESTIONS,
  "2-3": LESSON_2_3_DEEP_QUESTIONS,
};
