import { CommitteeQuestion, CommitteeQuestionType, CognitiveLevel, DifficultyLevel } from "./types";
import { CURRICULUM_DATA } from "@/data/curriculum";

/**
 * Base curated questions directly extracted and verified from the Egyptian Ministry of Education
 * Textbook "البرمجة والذكاء الاصطناعي - الصف الثاني الثانوي (بكالوريا مصرية) - الترم الأول".
 */

// Helper to safely convert existing curriculum questions to CommitteeQuestion
function convertCurriculumQuestions(): CommitteeQuestion[] {
  const result: CommitteeQuestion[] = [];

  CURRICULUM_DATA.forEach((ch) => {
    ch.lessons.forEach((l) => {
      l.questions.forEach((q, qIndex) => {
        let questionType: CommitteeQuestionType = "mcq";
        let cognitiveLevel: CognitiveLevel = "recall";
        let difficulty: DifficultyLevel = "medium";
        let marks = q.marks || 2;
        let estimatedTime = 1.5;

        if (q.type === "mcq") {
          questionType = "mcq";
          if (qIndex < 5) {
            cognitiveLevel = "recall";
            difficulty = "easy";
            marks = 1;
            estimatedTime = 1;
          } else if (qIndex < 8) {
            cognitiveLevel = "understanding";
            difficulty = "medium";
            marks = 2;
            estimatedTime = 1.5;
          } else {
            cognitiveLevel = "analysis";
            difficulty = "hard";
            marks = 2;
            estimatedTime = 2;
          }
        } else if (q.type === "true_false") {
          questionType = "true_false";
          cognitiveLevel = "understanding";
          difficulty = "medium";
          marks = 1.5;
          estimatedTime = 1;
        } else if (q.type === "fill_blank") {
          questionType = "complete";
          cognitiveLevel = "recall";
          difficulty = "easy";
          marks = 2;
          estimatedTime = 1.5;
        } else if (q.type === "essay") {
          questionType = "essay";
          cognitiveLevel = "higher_order";
          difficulty = "hard";
          marks = 6;
          estimatedTime = 6;
        }

        const exactAnswerStr = Array.isArray(q.correctAnswer)
          ? q.correctAnswer.join(" / ")
          : typeof q.correctAnswer === "object"
          ? JSON.stringify(q.correctAnswer)
          : String(q.correctAnswer);

        result.push({
          id: `CQ-${q.id}`,
          chapterId: ch.id,
          chapterNumber: ch.number,
          chapterTitle: ch.title,
          lessonId: l.id,
          lessonNumber: l.number,
          lessonTitle: l.title,
          topic: l.title,
          page: l.pageRange,
          sourceSection: `تمارين نهاية الدرس ${l.number}`,
          sourceReference: `الفصل ${ch.number} (${ch.title}) → الدرس ${l.number} → ص ${l.pageRange}`,
          questionType,
          difficulty,
          cognitiveLevel,
          question: q.questionText,
          modelAnswer: exactAnswerStr,
          textbookExactAnswer: exactAnswerStr,
          explanation: q.explanation,
          rubricCriteria: q.rubricCriteria,
          options: q.options,
          marks,
          estimatedTimeMinutes: estimatedTime,
          keywords: [l.title, ch.title, q.type],
        });
      });
    });
  });

  return result;
}

// Additional Specialized Committee Questions for:
// - Scientific Terminology (اكتب المصطلح العلمي)
// - Give Reasons / Justification (علل لما يأتي)
// - Comparisons (قارن وميز في جدول)
// - What Happens If / Consequences (ماذا يحدث إذا)
// - Arrange in Order (رتب بالترتيب الصحيح)
// - Classify (صنف العناصر)
// - Choose Odd Item (اختر الكلمة الشاذة مع التعليل)
// - Matching (صل من أ ما يناسبه من ب)
// - Cross-Lesson Synthesis (أسئلة ربط تكاملية بين الدروس)
const SPECIALIZED_COMMITTEE_QUESTIONS: CommitteeQuestion[] = [
  // ==========================================
  // CHAPTER 1 - LESSON 1-1
  // ==========================================
  {
    id: "CQ-SPEC-1-1-TERM-1",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-1",
    lessonNumber: "1-1",
    lessonTitle: "تطور تكنولوجيا المعلومات والتحول الاجتماعي",
    topic: "تاريخ تكنولوجيا المعلومات وقانون مور",
    page: "6 - 7",
    sourceSection: "مصطلحات أساسية وقانون مور",
    sourceReference: "الفصل 1 → الدرس 1-1 → تاريخ تكنولوجيا المعلومات → ص 6 - 7",
    questionType: "term",
    difficulty: "easy",
    cognitiveLevel: "recall",
    question: "اكتب المصطلح العلمي الدال على العبارة الآتية: «الملاحظة القائلة إن عدد الترانزستورات في الشريحة يتضاعف تقريبًا كل عامين».",
    modelAnswer: "قانون مور (Moore's Law)",
    textbookExactAnswer: "قانون مور: الملاحظة القائلة إن عدد الترانزستورات في الشريحة يتضاعف تقريبًا كل عامين.",
    explanation: "صاغ غوردون مور هذه الملاحظة عام 1965، وهي اتجاه تاريخي تجريبي وليست قانوناً فيزيائياً مطلقاً.",
    marks: 2,
    estimatedTimeMinutes: 1.5,
    keywords: ["قانون مور", "ترانزستورات", "شريحة", "عامين"],
  },
  {
    id: "CQ-SPEC-1-1-TERM-2",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-1",
    lessonNumber: "1-1",
    lessonTitle: "تطور تكنولوجيا المعلومات والتحول الاجتماعي",
    topic: "التقنيات الناشئة",
    page: "7 - 8",
    sourceSection: "الحوسبة الطرفية",
    sourceReference: "الفصل 1 → الدرس 1-1 → تقنيات ناشئة بارزة → ص 7 - 8",
    questionType: "term",
    difficulty: "medium",
    cognitiveLevel: "recall",
    question: "اكتب المصطلح العلمي: «معالجة البيانات على الجهاز نفسه، فورًا، بدلًا من إرسالها إلى السحابة لتقليل زمن الاستجابة».",
    modelAnswer: "الحوسبة الطرفية (Edge Computing)",
    textbookExactAnswer: "الحوسبة الطرفية: معالجة البيانات على الجهاز نفسه، فورًا، بدلًا من إرسالها إلى السحابة.",
    explanation: "تعتبر الحوسبة الطرفية ضرورية في التطبيقات الحساسة للوقت مثل السيارات ذاتية القيادة لتفادي التأخير والحوادث.",
    marks: 2,
    estimatedTimeMinutes: 1.5,
    keywords: ["الحوسبة الطرفية", "Edge Computing", "معالجة فورية"],
  },
  {
    id: "CQ-SPEC-1-1-REASON-1",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-1",
    lessonNumber: "1-1",
    lessonTitle: "تطور تكنولوجيا المعلومات والتحول الاجتماعي",
    topic: "السيارات ذاتية القيادة والحوسبة الطرفية",
    page: "7 - 8",
    sourceSection: "توقف وفكر - القيادة الذاتية",
    sourceReference: "الفصل 1 → الدرس 1-1 → تقنيات ناشئة بارزة → ص 7 - 8",
    questionType: "give_reason",
    difficulty: "medium",
    cognitiveLevel: "understanding",
    question: "علل لما يأتي: «في السيارات ذاتية القيادة، يُعد من الضروري معالجة البيانات فورًا على المركبة بالحوسبة الطرفية بدلاً من إرسالها إلى السحابة لاتخاذ القرارات الحساسة».",
    modelAnswer: "لأن التأخير في معالجة بيانات القيادة قد يؤثر مباشرة على سلامة الركاب والمشاة ويتسبب في حوادث؛ لذلك تُعالج البيانات محلياً بالحوسبة الطرفية لتقليل زمن الاستجابة (Latency) إلى أجزاء من الثانية دون انتظار اتصال السحابة.",
    textbookExactAnswer: "وألن التأخير في معالجة بيانات القيادة قد يؤثر في السالمة، تُعالج بعض البيانات محليًا بالحوسبة الطرفية لتقليل زمن الاستجابة.",
    marks: 3,
    estimatedTimeMinutes: 2,
    keywords: ["القيادة الذاتية", "الحوسبة الطرفية", "زمن الاستجابة", "السلامة"],
  },
  {
    id: "CQ-SPEC-1-1-REASON-2",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-1",
    lessonNumber: "1-1",
    lessonTitle: "تطور تكنولوجيا المعلومات والتحول الاجتماعي",
    topic: "قانون مور والتحديات الفيزيائية",
    page: "6",
    sourceSection: "قانون مور والتحديات الفيزيائية",
    sourceReference: "الفصل 1 → الدرس 1-1 → تاريخ تكنولوجيا المعلومات → ص 6",
    questionType: "give_reason",
    difficulty: "hard",
    cognitiveLevel: "understanding",
    question: "علل: «يواجه استمرار تصغير مكونات الدوائر المتكاملة تحديات هندسية وفيزيائية تبطئ الاتجاه الذي وصفه قانون مور».",
    modelAnswer: "بسبب ظهور تحديات فيزيائية كمومية دقيقة ناتجة عن وصول الترانزستورات إلى أحجام ذرية، ومنها ازدياد تيارات التسرب وتأثيرات النفق الكمومي وتوليد الحرارة الفائقة.",
    textbookExactAnswer: "لكن استمرار تصغير مكونات الدوائر يواجه تحديات هندسية وفيزيائية، منها ازدياد تيارات التسرب وتأثيرات كمومية مثل النفق الكمومي.",
    marks: 3,
    estimatedTimeMinutes: 2.5,
    keywords: ["قانون مور", "النفق الكمومي", "تيارات التسرب", "تصغير المكونات"],
  },
  {
    id: "CQ-SPEC-1-1-COMPARE-1",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-1",
    lessonNumber: "1-1",
    lessonTitle: "تطور تكنولوجيا المعلومات والتحول الاجتماعي",
    topic: "الواقع المعزز والواقع الافتراضي",
    page: "7 - 8",
    sourceSection: "الواقع المعزز / الواقع الافتراضي",
    sourceReference: "الفصل 1 → الدرس 1-1 → تقنيات ناشئة بارزة → ص 7 - 8",
    questionType: "compare",
    difficulty: "medium",
    cognitiveLevel: "analysis",
    question: "قارن في جدول منظم بين «الواقع المعزز (AR)» و«الواقع الافتراضي (VR)» من حيث: المفهوم، وكيفية تفاعل المستخدم مع بيئة العالم الحقيقي.",
    modelAnswer: "1. الواقع المعزز (AR): يضيف عناصر ومعلومات رقمية فوق مشهد من العالم الحقيقي، ويظل المستخدم متصلاً ببيئته الفعلية.\n2. الواقع الافتراضي (VR): يضع المستخدم بالكامل داخل بيئة افتراضية مولدة حاسوبياً ويعزله عن رؤية العالم الحقيقي المحيط به.",
    textbookExactAnswer: "الواقع المعزز (AR) يضيف عناصر رقمية إلى مشهد من العالم الحقيقي، بينما الواقع الافتراضي (VR) يضع المستخدم داخل بيئة افتراضية مولدة حاسوبيًا.",
    marks: 4,
    estimatedTimeMinutes: 3,
    keywords: ["AR", "VR", "الواقع المعزز", "الواقع الافتراضي"],
  },
  {
    id: "CQ-SPEC-1-1-ORDER-1",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-1",
    lessonNumber: "1-1",
    lessonTitle: "تطور تكنولوجيا المعلومات والتحول الاجتماعي",
    topic: "المراحل الزمنية لتطور IT",
    page: "5 - 6",
    sourceSection: "تاريخ تكنولوجيا المعلومات",
    sourceReference: "الفصل 1 → الدرس 1-1 → جدول المراحل التاريخية → ص 5 - 6",
    questionType: "order",
    difficulty: "medium",
    cognitiveLevel: "analysis",
    question: "رتب المراحل التاريخية الآتية لتطور تكنولوجيا المعلومات ترتيباً زمنياً تصاعدياً من الأقدم إلى الأحدث: (انتشار الحوسبة السحابية - ظهور الحواسيب الإلكترونية الأولى كـ ENIAC - إتاحة الإنترنت للاستخدام التجاري - ظهور الحواسيب الشخصية PCs - انتشار الهواتف الذكية).",
    modelAnswer: "1. ظهور الحواسيب الإلكترونية الأولى (ENIAC) والصمامات المفرغة (الأربعينيات-الستينيات)\n2. ظهور وانتشار الحواسيب الشخصية PCs (السبعينيات-الثمانينيات)\n3. إتاحة الإنترنت للاستخدام التجاري وظهور الويب (التسعينيات)\n4. ظهور وانتشار الهواتف الذكية (العقد الأول من الألفية)\n5. انتشار الحوسبة السحابية وتحليل البيانات الضخمة (العقد الثاني من الألفية فصاعداً)",
    textbookExactAnswer: "الترتيب الصحيح: الحواسيب الأولى (ENIAC) ← الحواسب الشخصية (PCs) ← إتاحة الإنترنت تجاريًا والويب ← ظهور الهواتف الذكية ← انتشار الحوسبة السحابية.",
    orderItems: [
      "ظهور الحواسيب الإلكترونية الأولى والصمامات المفرغة (ENIAC)",
      "انتشار الحواسب الشخصية (PCs) للأفراد",
      "إتاحة الإنترنت تجارياً وظهور شبكة الويب والبريد الإلكتروني",
      "ظهور وانتشار الهواتف الذكية وتطبيقاتها",
      "انتشار الحوسبة السحابية والبيانات الضخمة والذكاء الاصطناعي كخدمة",
    ],
    marks: 4,
    estimatedTimeMinutes: 3,
    keywords: ["ترتيب تاريخي", "ENIAC", "PCs", "الإنترنت", "السحابية"],
  },
  {
    id: "CQ-SPEC-1-1-ODD-1",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-1",
    lessonNumber: "1-1",
    lessonTitle: "تطور تكنولوجيا المعلومات والتحول الاجتماعي",
    topic: "التقنيات الناشئة",
    page: "7 - 8",
    sourceSection: "التقنيات الناشئة البارزة",
    sourceReference: "الفصل 1 → الدرس 1-1 → تقنيات ناشئة بارزة → ص 7 - 8",
    questionType: "odd_one_out",
    difficulty: "medium",
    cognitiveLevel: "analysis",
    question: "اختر العنصر غير المناسب (الشاذ) مع بيان السبب العلمي: (القيادة الذاتية - الواقع المعزز - الصمامات المفرغة - الحوسبة الكمومية - الحوسبة الطرفية).",
    modelAnswer: "العنصر غير المناسب هو: «الصمامات المفرغة».\nالسبب: لأنها تقنية قديمة تعود للمرحلة الأولى للحواسيب (الأربعينيات-الستينيات)، بينما باقي العناصر تمثل تقنيات ناشئة حديثة غيرت المجتمع في العقود الحالية.",
    textbookExactAnswer: "الصمامات المفرغة تقنية من القرن العشرين، بينما القيادة الذاتية، AR، الحوسبة الكمومية، والطرفية هي تقنيات ناشئة حديثة.",
    oddItemData: {
      items: ["القيادة الذاتية", "الواقع المعزز", "الصمامات المفرغة", "الحوسبة الكمومية", "الحوسبة الطرفية"],
      oddItem: "الصمامات المفرغة",
      reason: "الصمامات المفرغة من تقنيات الجيل الأول القديمة، بينما باقي العناصر تقنيات ناشئة حديثة.",
    },
    marks: 3,
    estimatedTimeMinutes: 2,
    keywords: ["الكلمة الشاذة", "تقنيات ناشئة", "صمامات مفرغة"],
  },
  {
    id: "CQ-SPEC-1-1-MATCH-1",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-1",
    lessonNumber: "1-1",
    lessonTitle: "تطور تكنولوجيا المعلومات والتحول الاجتماعي",
    topic: "التحولات الاجتماعية للتقنية",
    page: "6",
    sourceSection: "التغيرات الاجتماعية الناتجة عن تكنولوجيا المعلومات",
    sourceReference: "الفصل 1 → الدرس 1-1 → التغيرات الاجتماعية → ص 6",
    questionType: "matching",
    difficulty: "easy",
    cognitiveLevel: "recall",
    question: "صل من العمود (أ) ما يناسبه بدقة من العمود (ب):",
    modelAnswer: "1 يناسبها (جـ) - 2 يناسبها (أ) - 3 يناسبها (د) - 4 يناسبها (ب)",
    textbookExactAnswer: "شبكات التواصل الاجتماعي: نشر المحتوى والتواصل. التجارة الإلكترونية: بيع وشراء السلع عبر الإنترنت. العمل عن بعد: أداء المهام من المنزل. الدفع غير النقدي: وسائل دفع دون استخدام أوراق النقد.",
    matchingPairs: [
      { id: "m1", left: "1. التجارة الإلكترونية (E-commerce)", right: "بيع وشراء السلع والخدمات عبر المتاجر الرقمية" },
      { id: "m2", left: "2. شبكات التواصل الاجتماعي (SNS)", right: "منصات تتيح نشر المحتوى ومشاركته والتواصل الفوري" },
      { id: "m3", left: "3. العمل عن بُعد (Remote Work)", right: "أداء المهام الوظيفية من المنزل عبر الإنترنت" },
      { id: "m4", left: "4. الدفع غير النقدي (Cashless Payment)", right: "سداد المشتريات بالبطاقات أو رموز QR دون أوراق نقدية" },
    ],
    marks: 4,
    estimatedTimeMinutes: 2.5,
    keywords: ["توصيل", "E-commerce", "SNS", "Cashless"],
  },

  // ==========================================
  // CHAPTER 1 - LESSON 1-2
  // ==========================================
  {
    id: "CQ-SPEC-1-2-TERM-1",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-2",
    lessonNumber: "1-2",
    lessonTitle: "كيف يعمل الذكاء الاصطناعي",
    topic: "مفاهيم ومستويات الذكاء الاصطناعي",
    page: "12 - 14",
    sourceSection: "المفاهيم الأساسية",
    sourceReference: "الفصل 1 → الدرس 1-2 → هرم الذكاء الاصطناعي → ص 12 - 14",
    questionType: "term",
    difficulty: "easy",
    cognitiveLevel: "recall",
    question: "اكتب المصطلح العلمي: «مجال فرعي من تعلم الآلة يعتمد على شبكات عصبية اصطناعية متعددة الطبقات لمعالجة البيانات المعقدة كالصور والصوت».",
    modelAnswer: "التعلم العميق (Deep Learning)",
    textbookExactAnswer: "التعلم العميق (Deep Learning): مجموعة فرعية من التعلم الآلي تعتمد على شبكات عصبية اصطناعية عميقة متعددة الطبقات لمعالجة البيانات المعقدة.",
    explanation: "التعلم العميق هو جزء فرعي من تعلم الآلة، ويتميز بقدرته على استخراج الخصائص تلقائياً دون تدخل يدوي.",
    marks: 2,
    estimatedTimeMinutes: 1.5,
    keywords: ["التعلم العميق", "Deep Learning", "شبكات عصبية", "طبقات متعددة"],
  },
  {
    id: "CQ-SPEC-1-2-TERM-2",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-2",
    lessonNumber: "1-2",
    lessonTitle: "كيف يعمل الذكاء الاصطناعي",
    topic: "الذكاء الاصطناعي التوليدي والهلوسة",
    page: "15 - 16",
    sourceSection: "ظاهرة الهلوسة",
    sourceReference: "الفصل 1 → الدرس 1-2 → مخاطر الذكاء التوليدي → ص 15 - 16",
    questionType: "term",
    difficulty: "medium",
    cognitiveLevel: "recall",
    question: "اكتب المصطلح العلمي: «الحالة التي يولّد فيها نموذج الذكاء الاصطناعي إجابات غير صحيحة أو خيالية تماماً ويعرضها بثقة عالية كأنها حقائق مؤكدة».",
    modelAnswer: "الهلوسة في الذكاء الاصطناعي (AI Hallucination)",
    textbookExactAnswer: "الهلوسة (Hallucination): ظاهرة يقدم فيها نموذج الذكاء الاصطناعي معلومات غير صحيحة أو مخترعة بثقة تبدو مقنعة.",
    explanation: "تحدث الهلوسة لأن نماذج اللغة التوليدية تتوقع الكلمة التالية إحصائياً بناءً على الأنماط وليست محركات بحث تدرك الحقيقة المطلقة.",
    marks: 2,
    estimatedTimeMinutes: 1.5,
    keywords: ["الهلوسة", "Hallucination", "معلومات غير صحيحة", "ثقة مقنعة"],
  },
  {
    id: "CQ-SPEC-1-2-REASON-1",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-2",
    lessonNumber: "1-2",
    lessonTitle: "كيف يعمل الذكاء الاصطناعي",
    topic: "علاقة الذكاء الاصطناعي بتعلم الآلة",
    page: "13",
    sourceSection: "هرم الذكاء الاصطناعي",
    sourceReference: "الفصل 1 → الدرس 1-2 → هرمية الذكاء الاصطناعي → ص 13",
    questionType: "give_reason",
    difficulty: "medium",
    cognitiveLevel: "understanding",
    question: "علل: «كل تعلّم عميق هو تعلّم آلي، ولكن ليس كل تعلّم آلي هو تعلّماً عميقاً».",
    modelAnswer: "لأن التعلم العميق هو مجموعة فرعية متخصصة تقع بالكامل داخل التعلم الآلي وتعتمد حصراً على الشبكات العصبية العميقة، بينما يشمل التعلم الآلي خوارزميات ونماذج أخرى متعددة غير عميقة مثل الانحدار الخطي وأشجار القرار ومصنفات بايز.",
    textbookExactAnswer: "التعلم العميق هو جزء فرعي من التعلم الآلي، والتعلم الآلي بدوره جزء فرعي من الذكاء الاصطناعي العام.",
    marks: 3,
    estimatedTimeMinutes: 2,
    keywords: ["التعلم العميق", "التعلم الآلي", "هرمية", "شبكات عصبية"],
  },
  {
    id: "CQ-SPEC-1-2-WHATIF-1",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-2",
    lessonNumber: "1-2",
    lessonTitle: "كيف يعمل الذكاء الاصطناعي",
    topic: "التحقق من مخرجات الذكاء التوليدي",
    page: "15 - 16",
    sourceSection: "تقييم مخاطر الهلوسة",
    sourceReference: "الفصل 1 → الدرس 1-2 → مخاطر الهلوسة والتحقق البشري → ص 15 - 16",
    questionType: "what_if",
    difficulty: "hard",
    cognitiveLevel: "application",
    question: "ماذا يحدث لو: «اعتمد طبيب أو مهندس معماري اعتماداً كلياً على مخرجات روبوت ذكاء اصطناعي توليدي لتشخيص مريض أو حساب أحمال بناء دون مراجعة بشرية مستندة للأدلة؟»",
    modelAnswer: "قد يؤدي ذلك إلى كوارث صحية أو انهيارات إنشائية جسيمة؛ بسبب احتمالية تعرض النموذج لظاهرة «الهلوسة» واختلاق بيانات وتوصيات غير دقيقة بثقة مقنعة، مما يبرز حتمية وجود الإنسان في حلقة القرار (Human-in-the-Loop) والتحقق من المراجع الرسمية الموثوقة.",
    textbookExactAnswer: "الاعتماد دون تدقيق قد يسبب أخطاء فادحة بسبب الهلوسة، والتحقق البشري ضروري لضمان دقة وسلامة المخرجات الحساسة.",
    marks: 4,
    estimatedTimeMinutes: 3,
    keywords: ["ماذا يحدث لو", "الهلوسة", "التحقق البشري", "سلامة القرارات"],
  },
  {
    id: "CQ-SPEC-1-2-CLASSIFY-1",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-2",
    lessonNumber: "1-2",
    lessonTitle: "كيف يعمل الذكاء الاصطناعي",
    topic: "تصنيف مهام الذكاء الاصطناعي",
    page: "12 - 15",
    sourceSection: "أنواع ومستويات الذكاء الاصطناعي",
    sourceReference: "الفصل 1 → الدرس 1-2 → أقسام الذكاء الاصطناعي → ص 12 - 15",
    questionType: "classify",
    difficulty: "hard",
    cognitiveLevel: "analysis",
    question: "صنف التطبيقات والمهام التالية داخل الجدول حسب المستوى التقني الأنسب لها: (إنشاء قصة مصورة ومقال أدبي جديد - تصنيف الرسائل المزعجة Spam بالأشجار البسيطة - تمييز الأورام المعقدة بالأشعة عبر شبكات CNN متعددة الطبقات - نظام خبير قديم يعتمد على شروط If-Then صريحة):\n1. ذكاء اصطناعي قائم على القواعد\n2. تعلم آلي تقليدي (Machine Learning)\n3. تعلم عميق (Deep Learning)\n4. ذكاء اصطناعي توليدي (Generative AI)",
    modelAnswer: "1. قائم على القواعد: نظام خبير قديم يعتمد على شروط If-Then صريحة.\n2. تعلم آلي تقليدي: تصنيف الرسائل المزعجة Spam بالأشجار البسيطة.\n3. تعلم عميق: تمييز الأورام المعقدة بالأشعة عبر شبكات CNN متعددة الطبقات.\n4. ذكاء اصطناعي توليدي: إنشاء قصة مصورة ومقال أدبي جديد.",
    textbookExactAnswer: "الأنظمة المعتمدة على قواعد هي برامج كلاسيكية. التعلم الآلي يتعلم من الأنماط. التعلم العميق يحلل الصور والصوت المعقد بشبكات عصبية. التوليدي يبتكر محتوى غير مسبوق.",
    classificationData: {
      categories: ["قائم على القواعد", "تعلم آلي تقليدي", "تعلم عميق", "ذكاء توليدي"],
      items: [
        { item: "نظام خبير بقواعد If-Then", category: "قائم على القواعد" },
        { item: "فلترة رسائل البريد Spam", category: "تعلم آلي تقليدي" },
        { item: "تحليل صور الأشعة بشبكات CNN", category: "تعلم عميق" },
        { item: "كتابة مقال أو توليد صور جديدة", category: "ذكاء توليدي" },
      ],
    },
    marks: 4,
    estimatedTimeMinutes: 3,
    keywords: ["تصنيف", "قواعد", "تعلم آلي", "تعلم عميق", "ذكاء توليدي"],
  },

  // ==========================================
  // CHAPTER 1 - LESSON 1-3 & 1-4
  // ==========================================
  {
    id: "CQ-SPEC-1-4-TERM-1",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-4",
    lessonNumber: "1-4",
    lessonTitle: "القضايا الأخلاقية للذكاء الاصطناعي",
    topic: "التحيز الخوارزمي",
    page: "24 - 26",
    sourceSection: "المفاهيم الأساسية",
    sourceReference: "الفصل 1 → الدرس 1-4 → القضايا الأخلاقية → ص 24 - 26",
    questionType: "term",
    difficulty: "medium",
    cognitiveLevel: "recall",
    question: "اكتب المصطلح العلمي: «الميل المنهجي لنظام الذكاء الاصطناعي نحو اتخاذ قرارات تفضل فئة معينة على أخرى بطريقة غير عادلة بسبب عيوب في بيانات التدريب».",
    modelAnswer: "التحيز الخوارزمي (Algorithmic Bias)",
    textbookExactAnswer: "التحيز (Bias): ميل النظام إلى تفضيل مجموعة على أخرى بطريقة غير عادلة ناتج غالبًا عن بيانات تدريب غير متوازنة.",
    marks: 2,
    estimatedTimeMinutes: 1.5,
    keywords: ["التحيز الخوارزمي", "Algorithmic Bias", "بيانات غير متوازنة"],
  },
  {
    id: "CQ-SPEC-1-4-EXPLAIN-1",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-4",
    lessonNumber: "1-4",
    lessonTitle: "القضايا الأخلاقية للذكاء الاصطناعي",
    topic: "قابلية التفسير والشفافية والصندوق الأسود",
    page: "26 - 27",
    sourceSection: "الشفافية والمساءلة",
    sourceReference: "الفصل 1 → الدرس 1-4 → الشفافية والمساءلة → ص 26 - 27",
    questionType: "explain",
    difficulty: "hard",
    cognitiveLevel: "understanding",
    question: "اشرح باختصار المقصود بمشكلة «الصندوق الأسود (Black Box)» في نماذج الذكاء الاصطناعي، وبيّن لماذا تمثل تحدياً أخلاقياً وقانونياً في اتخاذ القرارات المصيرية كالعدالة والائتمان البنكي.",
    modelAnswer: "الصندوق الأسود يعني صعوبة أو استحالة فهم وتفسير الآلية الداخلية التي اتبعها النموذج للوصول إلى قرار محدد بسبب تعقيد ملايين الأوزان العصبية.\nويمثل تحدياً أخلاقياً وقانونياً لأنه يحرم المتضررين من معرفة سبب رفض توظيفهم أو حرمانهم من قرض أو إدانتهم، مما يتعارض مع مبادئ العدالة والمساءلة القانونية وحق الإنسان في التفسير.",
    textbookExactAnswer: "الشفافية تعني وضوح كيفية اتخاذ القرار. نماذج الصندوق الأسود تجعل من الصعب تبرير القرار أمام المتأثرين به وتعيق المساءلة القانونية.",
    marks: 4,
    estimatedTimeMinutes: 3,
    keywords: ["الصندوق الأسود", "Black Box", "قابلية التفسير", "الشفافية"],
  },

  // ==========================================
  // CHAPTER 2 - CYBERSECURITY
  // ==========================================
  {
    id: "CQ-SPEC-2-1-COMPARE-1",
    chapterId: "chapter-2",
    chapterNumber: 2,
    chapterTitle: "الأمن السيبراني",
    lessonId: "lesson-2-1",
    lessonNumber: "2-1",
    lessonTitle: "تقنيات التشفير والمصادقة",
    topic: "التشفير المتماثل وغير المتماثل",
    page: "31 - 34",
    sourceSection: "أنواع التشفير",
    sourceReference: "الفصل 2 → الدرس 2-1 → تقنيات التشفير → ص 31 - 34",
    questionType: "compare",
    difficulty: "hard",
    cognitiveLevel: "analysis",
    question: "قارن في جدول مقارنة علمي دقيق بين «التشفير المتماثل (Symmetric)» و«التشفير غير المتماثل (Asymmetric)» من حيث: عدد المفاتيح المستخدمة، السرعة، والتحدي الرئيسي في الاستخدام.",
    modelAnswer: "1. التشفير المتماثل:\n- عدد المفاتيح: مفتاح سري واحد مشترك للتشفير وفك التشفير.\n- السرعة: سريع جداً ومناسب لتشفير كميات البيانات الكبيرة.\n- التحدي: كيفية نقل المفتاح السري المشترك بأمان بين الطرفين.\n\n2. التشفير غير المتماثل:\n- عدد المفاتيح: زوج من المفاتيح (مفتاح عام Public ومفتاح خاص Private).\n- السرعة: أبطأ حوسبياً ويستهلك معالجة أكبر.\n- التحدي: البطء النسبي؛ لذا يُستخدم لتبادل المفاتيح السرية أو التوقيع الرقمي.",
    textbookExactAnswer: "التشفير المتماثل يستخدم مفتاحًا واحدًا للتشفير وفك التشفير وهو سريع. التشفير غير المتماثل يستخدم مفتاحين (عام وخاص)، ويحل مشكلة توزيع المفاتيح.",
    marks: 4,
    estimatedTimeMinutes: 3.5,
    keywords: ["تشفير متماثل", "تشفير غير متماثل", "مفتاح عام", "مفتاح خاص"],
  },
  {
    id: "CQ-SPEC-2-1-TERM-1",
    chapterId: "chapter-2",
    chapterNumber: 2,
    chapterTitle: "الأمن السيبراني",
    lessonId: "lesson-2-1",
    lessonNumber: "2-1",
    lessonTitle: "تقنيات التشفير والمصادقة",
    topic: "المصادقة متعددة العوامل",
    page: "34 - 36",
    sourceSection: "المصادقة والمصادقة متعددة العوامل",
    sourceReference: "الفصل 2 → الدرس 2-1 → المصادقة متعددة العوامل → ص 34 - 36",
    questionType: "term",
    difficulty: "easy",
    cognitiveLevel: "recall",
    question: "اكتب المصطلح العلمي: «آلية أمنية تتطلب من المستخدم تقديم دليلين أو أكثر لإثبات هويته من فئات مختلفة (مثل: كلمة المرور ورمز الهاتف وبصمة الإصبع)».",
    modelAnswer: "المصادقة متعددة العوامل (MFA - Multi-Factor Authentication)",
    textbookExactAnswer: "المصادقة متعددة العوامل (MFA): نظام أمني يتحقق من هوية المستخدم باستخدام عاملين أو أكثر من فئات مختلفة.",
    marks: 2,
    estimatedTimeMinutes: 1.5,
    keywords: ["MFA", "المصادقة متعددة العوامل", "إثبات الهوية"],
  },
  {
    id: "CQ-SPEC-2-2-TERM-1",
    chapterId: "chapter-2",
    chapterNumber: 2,
    chapterTitle: "الأمن السيبراني",
    lessonId: "lesson-2-2",
    lessonNumber: "2-2",
    lessonTitle: "تصميم أمن الشبكات",
    topic: "مفهوم الثقة الصفرية",
    page: "40 - 41",
    sourceSection: "مبدأ الثقة الصفرية",
    sourceReference: "الفصل 2 → الدرس 2-2 → أمن الشبكات → ص 40 - 41",
    questionType: "term",
    difficulty: "medium",
    cognitiveLevel: "recall",
    question: "اكتب المصطلح العلمي: «نموذج أمني للشبكات يرتكز على مبدأ: «لا تثق بأي مستخدم أو جهاز قط، وتحقق دائمًا» حتى لو كان متصلاً من داخل شبكة المؤسسة المحلية».",
    modelAnswer: "نموذج الثقة الصفرية (Zero Trust)",
    textbookExactAnswer: "الثقة الصفرية (Zero Trust): نهج أمني يفترض وجود تهديدات محتملة دائمًا، ويشترط التحقق المستمر والصارم من كل جهاز ومستخدم بصرف النظر عن موقعه.",
    marks: 2,
    estimatedTimeMinutes: 1.5,
    keywords: ["Zero Trust", "الثقة الصفرية", "تحقق دائم"],
  },
  {
    id: "CQ-SPEC-2-3-ORDER-1",
    chapterId: "chapter-2",
    chapterNumber: 2,
    chapterTitle: "الأمن السيبراني",
    lessonId: "lesson-2-3",
    lessonNumber: "2-3",
    lessonTitle: "الاستجابة للحوادث وإدارة المخاطر",
    topic: "دورة الاستجابة للحوادث الأمنية",
    page: "44 - 46",
    sourceSection: "دورة الاستجابة للحوادث",
    sourceReference: "الفصل 2 → الدرس 2-3 → الاستجابة للحوادث → ص 44 - 46",
    questionType: "order",
    difficulty: "hard",
    cognitiveLevel: "analysis",
    question: "رتب المراحل الخمس المعتمدة في دورة الاستجابة للحوادث السيبرانية (Incident Response Cycle) ترتيباً تسلسلياً دقيقاً: (الدروس المستفادة - الاستعداد والتأهب - الاحتواء والحد من الأثر - الكشف والتحليل - الاستئصال والتعافي).",
    modelAnswer: "1. الاستعداد والتأهب (Preparation)\n2. الكشف والتحليل (Detection & Analysis)\n3. الاحتواء (Containment)\n4. الاستئصال والتعافي (Eradication & Recovery)\n5. الدروس المستفادة (Lessons Learned)",
    textbookExactAnswer: "دورة الاستجابة للحوادث: الاستعداد ← الكشف والتحليل ← الاحتواء ← الاستئصال والتعافي ← الدروس المستفادة.",
    orderItems: [
      "الاستعداد والتأهب (وضع السياسات وتجهيز الأدوات والفرق)",
      "الكشف والتحليل (رصد النشاط المشبوه وتقييم نطاق الاختراق)",
      "الاحتواء (عزل الأنظمة المصابة ومنع انتشار الهجوم)",
      "الاستئصال والتعافي (حذف البرمجيات الخبيثة واستعادة البيانات الآمنة)",
      "الدروس المستفادة (توثيق الحادثة وتحديث الدفاعات لتفادي التكرار)",
    ],
    marks: 5,
    estimatedTimeMinutes: 3,
    keywords: ["الاستجابة للحوادث", "دورة الحوادث", "ترتيب مراحل الأمن"],
  },

  // ==========================================
  // CHAPTER 3 - WEB APPLICATIONS
  // ==========================================
  {
    id: "CQ-SPEC-3-1-EXPLAIN-1",
    chapterId: "chapter-3",
    chapterNumber: 3,
    chapterTitle: "تطبيقات الويب",
    lessonId: "lesson-3-1",
    lessonNumber: "3-1",
    lessonTitle: "البنية العامة لتطبيقات الويب",
    topic: "البنية ثلاثية الطبقات 3-Tier",
    page: "50 - 53",
    sourceSection: "البنية ثلاثية الطبقات",
    sourceReference: "الفصل 3 → الدرس 3-1 → بنية تطبيقات الويب → ص 50 - 53",
    questionType: "explain",
    difficulty: "medium",
    cognitiveLevel: "understanding",
    question: "اشرح باختصار دور كل طبقة من الطبقات الثلاث في بنية تطبيقات الويب (3-Tier Architecture)، موضحاً فائدة فصل طبقة منطق التطبيق عن طبقة قاعدة البيانات.",
    modelAnswer: "1. طبقة العرض (Presentation Tier): واجهة المستخدم التي تعمل على المتصفح وتستقبل مدخلات المستخدم.\n2. طبقة منطق التطبيق (Application Logic Tier): تعالج العمليات الحسابية وتنفذ قواعد العمل والأمان.\n3. طبقة البيانات (Data Tier): قاعدة البيانات التي تخزن وتسترجع البيانات بشكل منظم.\n- فائدة الفصل: تحسين الأمان (منع المستخدم من الوصول المباشر لقاعدة البيانات)، وسهولة الصيانة، وإمكانية تعديل قواعد العمل دون المساس بقاعدة البيانات أو واجهة العميل.",
    textbookExactAnswer: "البنية ثلاثية الطبقات تقسم التطبيق إلى: طبقة العرض (الواجهة)، وطبقة منطق التطبيق (المعالجة والقواعد)، وطبقة البيانات (التخزين). الفصل يعزز الأمان والأداء وقابلية التوسع.",
    marks: 4,
    estimatedTimeMinutes: 3,
    keywords: ["3-Tier", "بنية الويب", "طبقة العرض", "طبقة المنطق", "طبقة البيانات"],
  },
  {
    id: "CQ-SPEC-3-2-COMPARE-1",
    chapterId: "chapter-3",
    chapterNumber: 3,
    chapterTitle: "تطبيقات الويب",
    lessonId: "lesson-3-2",
    lessonNumber: "3-2",
    lessonTitle: "طرق الاتصال في تطبيقات الويب",
    topic: "بروتوكولات HTTP و HTTPS",
    page: "56 - 58",
    sourceSection: "بروتوكولات الويب وأمن الاتصال",
    sourceReference: "الفصل 3 → الدرس 3-2 → طرق الاتصال → ص 56 - 58",
    questionType: "compare",
    difficulty: "medium",
    cognitiveLevel: "analysis",
    question: "قارن بين بروتوكولي «HTTP» و«HTTPS» من حيث: استخدام التشفير، رقم المنفذ الافتراضي (Port)، ومستوى الأمان عند تداول كلمات المرور وبيانات الدفع.",
    modelAnswer: "1. بروتوكول HTTP:\n- التشفير: غير مشفر (نص واضح Plaintext).\n- المنفذ الافتراضي: 80.\n- الأمان: غير آمن ومعرض للتنصت وسرقة البيانات الحساسة.\n\n2. بروتوكول HTTPS:\n- التشفير: مشفر بالكامل باستخدام بروتوكول SSL/TLS.\n- المنفذ الافتراضي: 443.\n- الأمان: يوفر سرية وسلامة البيانات وحماية بيانات الدفع وكلمات المرور من التجسس والتعديل.",
    textbookExactAnswer: "بروتوكول HTTPS هو النسخة الآمنة من HTTP، ويستخدم تشفير SSL/TLS على المنفذ 443 لحماية سرية البيانات ومنع التنصت.",
    marks: 4,
    estimatedTimeMinutes: 2.5,
    keywords: ["HTTP", "HTTPS", "SSL/TLS", "منفذ 443", "منفذ 80"],
  },
  {
    id: "CQ-SPEC-3-3-MATCH-1",
    chapterId: "chapter-3",
    chapterNumber: 3,
    chapterTitle: "تطبيقات الويب",
    lessonId: "lesson-3-3",
    lessonNumber: "3-3",
    lessonTitle: "أساسيات تكنولوجيا الواجهة الأمامية",
    topic: "لغات الواجهة الأمامية الثلاث",
    page: "62 - 64",
    sourceSection: "ثلاثية الواجهة الأمامية",
    sourceReference: "الفصل 3 → الدرس 3-3 → تكنولوجيا الواجهة الأمامية → ص 62 - 64",
    questionType: "matching",
    difficulty: "easy",
    cognitiveLevel: "recall",
    question: "صل من العمود (أ) ما يناسبه بدقة من العمود (ب) لتحديد الدور الأساسي للغات الويب:",
    modelAnswer: "1 يناسبها (ب) - 2 يناسبها (جـ) - 3 يناسبها (أ)",
    textbookExactAnswer: "HTML تحدد هيكل ومحتوى الصفحة. CSS تحدد التنسيق والألوان والمظهر والتصميم المتجاوب. JavaScript تضيف التفاعلية والتحكم في نموذج DOM.",
    matchingPairs: [
      { id: "m3-1", left: "1. لغة HTML", right: "تحديد الهيكل البنائي ودلالات عناصر الصفحة (نصوص، عناوين، جداول)" },
      { id: "m3-2", left: "2. لغة CSS", right: "التحكم في التنسيقات البصرية والألوان والخطوط والتصميم المتجاوب" },
      { id: "m3-3", left: "3. لغة JavaScript", right: "إضافة التفاعلية الديناميكية والاستجابة لأحداث المستخدم وتعديل DOM" },
    ],
    marks: 3,
    estimatedTimeMinutes: 2,
    keywords: ["HTML", "CSS", "JavaScript", "توصيل"],
  },

  // ==========================================
  // CHAPTER 4 - WEB DESIGN & MEDIA
  // ==========================================
  {
    id: "CQ-SPEC-4-1-COMPARE-1",
    chapterId: "chapter-4",
    chapterNumber: 4,
    chapterTitle: "تصميم الويب والوسائط",
    lessonId: "lesson-4-1",
    lessonNumber: "4-1",
    lessonTitle: "أنواع الوسائط وخصائصها",
    topic: "الصور النقطية والمتجهة",
    page: "68 - 71",
    sourceSection: "الصور النقطية والمتجهة",
    sourceReference: "الفصل 4 → الدرس 4-1 → أنواع الوسائط → ص 68 - 71",
    questionType: "compare",
    difficulty: "medium",
    cognitiveLevel: "analysis",
    question: "قارن في جدول منظم بين «الصور النقطية (Raster/Bitmap)» و«الصور المتجهة (Vector)» من حيث: البنية الأساسية لتكوين الصورة، أثر التكبير والتصغير على الجودة، والمجال الأنسب لاستخدام كل منهما.",
    modelAnswer: "1. الصور النقطية (Raster):\n- البنية: شبكة من البكسلات الملونة (Pixels).\n- أثر التكبير: تفقد جودتها وتصبح منكسة/مشوشة (Pixelated) عند تكبيرها.\n- الاستخدام الأنسب: الصور الفوتوغرافية والمشاهد الغنية بالتدرجات الدقيقة (JPEG, PNG).\n\n2. الصور المتجهة (Vector):\n- البنية: خطوط ومنحنيات مبنية على معادلات رياضية.\n- أثر التكبير: تحتفظ بحدتها وجودتها الكاملة تماماً مهما كَبُر حجمها.\n- الاستخدام الأنسب: الشعارات (Logos)، الأيقونات، والرسوم التوضيحية (SVG).",
    textbookExactAnswer: "الصور النقطية تعتمد على شبكة بكسلات وتفقد جودتها عند التكبير (مثل صور الكاميرا). الصور المتجهة تعتمد على معادلات رياضية وتحافظ على وضوحها عند أي مقياس (مثل الشعارات و SVG).",
    marks: 4,
    estimatedTimeMinutes: 3,
    keywords: ["الصور النقطية", "الصور المتجهة", "Raster", "Vector", "SVG", "بكسل"],
  },
  {
    id: "CQ-SPEC-4-2-EXPLAIN-1",
    chapterId: "chapter-4",
    chapterNumber: 4,
    chapterTitle: "تصميم الويب والوسائط",
    lessonId: "lesson-4-2",
    lessonNumber: "4-2",
    lessonTitle: "تصميم المعلومات وتجربة المستخدم للمواقع",
    topic: "مبادئ التصميم الأربعة CRAP",
    page: "74 - 77",
    sourceSection: "مبادئ التصميم الأربعة (CRAP)",
    sourceReference: "الفصل 4 → الدرس 4-2 → تجربة المستخدم ومبادئ CRAP → ص 74 - 77",
    questionType: "explain",
    difficulty: "hard",
    cognitiveLevel: "analysis",
    question: "وضّح باختصار كيف يساهم كل مبدأ من مبادئ التصميم الأربعة (CRAP) في تحسين سهولة قراءة واستخدام الموقع الإلكتروني:\n1. التباين (Contrast)\n2. التكرار (Repetition)\n3. المحاذاة (Alignment)\n4. التقارب (Proximity)",
    modelAnswer: "1. التباين (Contrast): يجعل العناصر المهمة كالعناوين والأزرار بارزة وملفتة للنظر مقارنة بالخلفية.\n2. التكرار (Repetition): يوحد النمط البصري كالألوان والخطوط عبر صفحات الموقع ليمنحه هوية متناسقة ومألوفة.\n3. المحاذاة (Alignment): يربط عناصر الصفحة بصرياً على شبكة محكمة ليمنح الصفحة مظهراً منظماً ويسهل حركة العين.\n4. التقارب (Proximity): يضع العناصر المترابطة معاً في مجموعة واحدة، ويفصلها عن غيرها بمساحة فارغة لتنظيم العلاقات المنطقية.",
    textbookExactAnswer: "مبادئ CRAP: التباين لإبراز الأهمية، التكرار للاتساق البصري، المحاذاة للتنظيم والربط، والتقارب لتجميع العناصر المترابطة معًا.",
    marks: 4,
    estimatedTimeMinutes: 3.5,
    keywords: ["CRAP", "التباين", "التكرار", "المحاذاة", "التقارب"],
  },
  {
    id: "CQ-SPEC-4-3-TERM-1",
    chapterId: "chapter-4",
    chapterNumber: 4,
    chapterTitle: "تصميم الويب والوسائط",
    lessonId: "lesson-4-3",
    lessonNumber: "4-3",
    lessonTitle: "أساليب تقييم المواقع الإلكترونية",
    topic: "اختبار A/B واختبار قابلية الاستخدام",
    page: "81 - 84",
    sourceSection: "أساليب التقييم المعتمدة",
    sourceReference: "الفصل 4 → الدرس 4-3 → تقييم المواقع → ص 81 - 84",
    questionType: "term",
    difficulty: "medium",
    cognitiveLevel: "recall",
    question: "اكتب المصطلح العلمي: «منهجية تقييمية تجريبية يتم فيها عرض نسختين مختلفتين من صفحة الويب (A و B) على مجموعتين عشوائيتين من المستخدمين لمقارنة أيهما تحقق معدل نجاح أو نقرات أعلى بالاعتماد على البيانات الرقمية الفعلية».",
    modelAnswer: "اختبار أ/ب (A/B Testing)",
    textbookExactAnswer: "اختبار A/B: أسلوب مقارنة نسختين من صفحة ويب لعرضهما على مستخدمين حقيقيين وقياس أي النسختين تحقق أداءً أفضل في تحقيق الهدف.",
    marks: 2,
    estimatedTimeMinutes: 1.5,
    keywords: ["A/B Testing", "اختبار A/B", "مقارنة نسختين", "معدل التحويل"],
  },
  {
    id: "CQ-SPEC-4-4-ORDER-1",
    chapterId: "chapter-4",
    chapterNumber: 4,
    chapterTitle: "تصميم الويب والوسائط",
    lessonId: "lesson-4-4",
    lessonNumber: "4-4",
    lessonTitle: "عملية التحسين التكراري للمواقع",
    topic: "دورة التحسين المستمر PDCA",
    page: "87 - 89",
    sourceSection: "دورة التحسين التكراري PDCA",
    sourceReference: "الفصل 4 → الدرس 4-4 → التحسين التكراري → ص 87 - 89",
    questionType: "order",
    difficulty: "medium",
    cognitiveLevel: "understanding",
    question: "رتب خطوات دورة التحسين التكراري المستمر للمواقع (PDCA Cycle) ترتيباً صحيحاً: (Act: طوّر وتصرّف - Plan: خطط وحدد الأهداف - Check: افحص وقِس النتائج - Do: نفّذ التغييرات التجريبية).",
    modelAnswer: "1. Plan (خطط): تحديد المشكلة، ووضع الأهداف والفرضيات.\n2. Do (نفّذ): تطبيق التعديلات على نطاق تجريبي أو إطلاق النسخة المحسنة.\n3. Check (افحص): قياس مؤشرات الأداء، وتحليل النتائج والملاحظات.\n4. Act (طوّر/تصرّف): تعميم الحل الناجح، أو إجراء تعديلات إضافية وبدء دورة تحسين جديدة.",
    textbookExactAnswer: "دورة التحسين التكراري: خطط (Plan) ← نفّذ (Do) ← افحص (Check) ← طوّر/تصرّف (Act).",
    orderItems: [
      "Plan (خطط): دراسة سلوك المستخدم وتحديد المشكلة ووضع الحل المقترح",
      "Do (نفّذ): تطبيق التعديل المقترح واختباره عملياً",
      "Check (افحص): قياس مؤشرات الأداء وتحليل البيانات وردود الفعل",
      "Act (طوّر وتصرّف): تثبيت التعديل الناجح أو إعادة ضبط الفرضية للدورة القادمة",
    ],
    marks: 4,
    estimatedTimeMinutes: 2.5,
    keywords: ["PDCA", "دورة التحسين", "Plan Do Check Act"],
  },

  // ==========================================
  // CROSS-LESSON SYNTHESIS QUESTIONS (المستويات العليا والربط التكاملي)
  // ==========================================
  {
    id: "CQ-SPEC-CROSS-1",
    chapterId: "chapter-2",
    chapterNumber: 2,
    chapterTitle: "الأمن السيبراني",
    lessonId: "lesson-2-1",
    lessonNumber: "2-1",
    lessonTitle: "تقنيات التشفير والمصادقة",
    topic: "تكامل التشفير مع بروتوكول HTTPS في الويب",
    page: "31 - 37 و 56 - 61",
    sourceSection: "ربط تكاملي: التشفير غير المتماثل مع HTTPS",
    sourceReference: "الربط بين الفصل 2 (الدرس 2-1: التشفير والشهادات) والفصل 3 (الدرس 3-2: طرق الاتصال HTTPS)",
    questionType: "cross_lesson",
    difficulty: "higher_order",
    cognitiveLevel: "higher_order",
    question: "سؤال ربط تكاملي [المستويات العليا]: وضح كيف تتكامل تقنيات «التشفير غير المتماثل» و«الشهادات الرقمية» التي درستها في الفصل الثاني (الأمن السيبراني) مع بروتوكول «HTTPS» الذي درسته في الفصل الثالث (تطبيقات الويب)، موضحاً الخطوات التي تحدث عند بدء اتصال آمن بين المتصفح وخادم الويب.",
    modelAnswer: "الإجابة النموذجية:\n1) عند طلب العميل لموقع مشفر عبر HTTPS (منفذ 443)، يرسل الخادم «شهادة رقمية» موثقة من هيئة معتمدة (CA) تحتوي على المفتاح العام للخادم.\n2) يتحقق المتصفح من صحة الشهادة وهوية الموقع لحماية المستخدم من انتحال الشخصية.\n3) يستخدم المتصفح «المفتاح العام» للخادم لتشفير مفتاح جلسة سري عشوائي (Session Key) وإرساله بأمان.\n4) يقوم الخادم بفك تشفير مفتاح الجلسة باستخدام «مفتاحه الخاص» المقابل.\n5) بعد تأمين تبادل المفتاح، يتحول الاتصال إلى «التشفير المتماثل» السريع باستخدام مفتاح الجلسة المشترك لتشفير كافة حزم البيانات المنقولة بكفاءة وسرعة.",
    textbookExactAnswer: "بروتوكول HTTPS يدمج تشفير SSL/TLS باستخدام المفتاح العام والشهادة الرقمية للتأكد من هوية الخادم، وتبادل مفتاح سري لإتمام التشفير السريع لباقي الجلسة.",
    rubricCriteria: [
      "توضيح دور الشهادة الرقمية وهيئة CA في إثبات هوية الخادم (درجتان)",
      "شرح استخدام المفتاح العام لتشفير وتبادل مفتاح الجلسة السري (درجتان)",
      "بيان التحول للتشفير المتماثل باستخدام مفتاح الجلسة لضمان سرعة نقل البيانات (درجتان)",
    ],
    marks: 6,
    estimatedTimeMinutes: 5,
    isCrossLesson: true,
    connectedLessons: ["الدرس 2-1: تقنيات التشفير والمصادقة", "الدرس 3-2: طرق الاتصال في تطبيقات الويب"],
    keywords: ["ربط تكاملي", "HTTPS", "شهادة رقمية", "تشفير غير متماثل", "SSL/TLS"],
  },
  {
    id: "CQ-SPEC-CROSS-2",
    chapterId: "chapter-1",
    chapterNumber: 1,
    chapterTitle: "تكنولوجيا المعلومات والمجتمع",
    lessonId: "lesson-1-4",
    lessonNumber: "1-4",
    lessonTitle: "القضايا الأخلاقية للذكاء الاصطناعي",
    topic: "تكامل أخلاقيات الذكاء الاصطناعي مع معايير إتاحة الويب",
    page: "24 - 30 و 74 - 80",
    sourceSection: "ربط تكاملي: العدالة الرقمية وإتاحة الويب للمستخدمين",
    sourceReference: "الربط بين الفصل 1 (الدرس 1-4: القضايا الأخلاقية) والفصل 4 (الدرس 4-2: إتاحة الويب وتجربة المستخدم)",
    questionType: "cross_lesson",
    difficulty: "higher_order",
    cognitiveLevel: "higher_order",
    question: "سؤال ربط تكاملي [المستويات العليا]: ناقش كيف يرتبط مبدأ «العدالة الرقمية ومنع التحيز» في أخلاقيات الذكاء الاصطناعي (الفصل الأول) مع مبادئ «سهولة الوصول والإتاحة (Accessibility / WCAG)» في تصميم تجربة المستخدم للمواقع (الفصل الرابع)، مع تقديم مثالين عمليين لما يجب على المطور مراعاته لحماية الفئات المستضعفة.",
    modelAnswer: "الإجابة النموذجية:\nكلا المفهومان يهدفان إلى ضمان حق الوصول المتساوي والشامل لكافة أفراد المجتمع دون تمييز أو تهميش:\n1) في الذكاء الاصطناعي: يجب فحص بيانات التدريب لتفادي تفضيل فئات محددة وتهميش ذوي الإعاقة أو كبار السن أو الفئات الأقل تمثيلاً.\n2) في تصميم الويب: يجب تطبيق معايير الإتاحة لتمكين الجميع من استخدام الموقع بسلاسة.\n- مثالان عمليان للمطور:\nأ) توفير نصوص بديلة (Alt Text) للصور ووصف دقيق لقارئات الشاشة لذوي الإعاقة البصرية.\nب) تدريب واجهات التعرف على الصوت واللغة بالذكاء الاصطناعي على لهجات ونبرات صوتية متنوعة وفئات ذات صعوبات نطق لضمان عدالتها ودقتها للجميع.",
    textbookExactAnswer: "العدالة في الذكاء الاصطناعي تضمن عدم انحياز الأنظمة ضد فئات معينة، وهو ما يماثل في تصميم الويب مبادئ سهولة الوصول (Accessibility) لتمكين ذوي الإعاقة وكبار السن من الانتفاع بالخدمات الرقمية.",
    rubricCriteria: [
      "ربط مفهوم منع التحيز بمفهوم سهولة الوصول والشمولية الرقمية (درجتان)",
      "تقديم مثال تطبيقي في واجهات الويب مثل النصوص البديلة والتباين (درجتان)",
      "تقديم مثال تطبيقي في أنظمة الذكاء الاصطناعي وتنوع بيانات التدريب (درجتان)",
    ],
    marks: 6,
    estimatedTimeMinutes: 5,
    isCrossLesson: true,
    connectedLessons: ["الدرس 1-4: القضايا الأخلاقية للذكاء الاصطناعي", "الدرس 4-2: تصميم المعلومات وتجربة المستخدم للمواقع"],
    keywords: ["ربط تكاملي", "التحيز الخوارزمي", "إتاحة الويب", "Accessibility", "العدالة الرقمية"],
  },
  {
    id: "CQ-SPEC-CROSS-3",
    chapterId: "chapter-3",
    chapterNumber: 3,
    chapterTitle: "تطبيقات الويب",
    lessonId: "lesson-3-3",
    lessonNumber: "3-3",
    lessonTitle: "أساسيات تكنولوجيا الواجهة الأمامية",
    topic: "تكامل سرعة تحميل الواجهة الأمامية مع ضغط الوسائط في تصميم الويب",
    page: "62 - 67 و 68 - 73",
    sourceSection: "ربط تكاملي: الأداء والوسائط المتجاوبة",
    sourceReference: "الربط بين الفصل 3 (الدرس 3-3: الواجهة الأمامية) والفصل 4 (الدرس 4-1: ضغط الوسائط)",
    questionType: "cross_lesson",
    difficulty: "hard",
    cognitiveLevel: "higher_order",
    question: "سؤال ربط تكاملي [المستويات العليا]: حلل كيف يؤثر اختيار نوع وضغط الوسائط (الصور النقطية مقابل المتجهة) من الفصل الرابع تأثيراً مباشراً على مؤشرات أداء الواجهة الأمامية وتجربة المستخدم على الهواتف المحمولة في الفصل الثالث.",
    modelAnswer: "الإجابة النموذجية:\n1) حجم الملفات وسرعة التحميل: استخدام الصور المتجهة SVG للشعارات والأيقونات يقلل حجم الصفحة بشكل هائل لأنها كود نصوص وأشكال رياضية بدلاً من بكسلات ثقيلة.\n2) التوافق مع شاشات الهواتف ذات الكثافة العالية (Retina Screens): صور SVG تحتفظ بحدتها الفائقة على أي دقة شاشة متجاوبة دون الحاجة لتحميل صور نقطية مضاعفة الحجم.\n3) تقليل استهلاك باقة البيانات وزمن الاستجابة: تطبيق الضغط المناسب للصور الفوتوغرافية النقطية يسرع من اكتمال بناء شجرة DOM وتصيير الشاشة الأولى، مما يقلل معدل الارتداد (Bounce Rate) لدى مستخدمي الهواتف.",
    textbookExactAnswer: "اختيار التنسيق المناسب للوسائط (مثل SVG للأيقونات وضغط الصور النقطية) يقلل وقت تحميل الصفحة ويحسن التصميم المتجاوب على شاشات الهواتف.",
    rubricCriteria: [
      "شرح تفوق صور SVG في الحجم والحدة على الشاشات المتجاوبة (درجتان)",
      "ربط حجم ملفات الصور بسرعة بناء شجرة الواجهة الأمامية وتصييرها (درجتان)",
      "توضيح أثر سرعة التحميل على تقليل معدل الارتداد وتجربة مستخدمي الهواتف (درجتان)",
    ],
    marks: 6,
    estimatedTimeMinutes: 4.5,
    isCrossLesson: true,
    connectedLessons: ["الدرس 3-3: أساسيات تكنولوجيا الواجهة الأمامية", "الدرس 4-1: أنواع الوسائط وخصائصها"],
    keywords: ["ربط تكاملي", "SVG", "سرعة التحميل", "الواجهة الأمامية", "الهواتف المحمولة"],
  },
];

// Combine all questions into the master verified pool
let cachedQuestionPool: CommitteeQuestion[] | null = null;

export function getAllCommitteeQuestions(): CommitteeQuestion[] {
  if (!cachedQuestionPool) {
    const fromCurriculum = convertCurriculumQuestions();
    cachedQuestionPool = [...fromCurriculum, ...SPECIALIZED_COMMITTEE_QUESTIONS];
  }
  return cachedQuestionPool;
}
