import { ProfilePreset } from "./types";

export const EXAM_PROFILES: ProfilePreset[] = [
  {
    id: "quick_quiz",
    title: "اختبار سريع (Quick Quiz)",
    description: "اختبار تشخيصي رشيق من 10 إلى 15 سؤالاً للتحقق السريع من الاستيعاب المباشر والمفاهيم.",
    iconName: "Zap",
    badge: "15 دقيقة • 15 سؤالاً",
    config: {
      questionCount: 15,
      examCount: 1,
      difficultyPreset: "recall_heavy",
      difficultyDistribution: { easy: 50, medium: 35, hard: 15, higherOrder: 0 },
      durationMinutes: 15,
      totalMarks: 30,
      questionTypes: ["mcq", "true_false", "term", "complete"],
      randomizeQuestions: true,
      randomizeOptions: true,
      includeAnswers: false,
      includeSourceReferences: true,
      useExactBookAnswers: true,
    },
  },
  {
    id: "lesson_test",
    title: "اختبار الدرس التقييمي (Lesson Test)",
    description: "تقييم شامل لدرس واحد أو درسين متقاربين متدرج من الاسترجاع حتى التحليل والتطبيق.",
    iconName: "BookOpen",
    badge: "30 دقيقة • 25 سؤالاً",
    config: {
      questionCount: 25,
      examCount: 1,
      difficultyPreset: "balanced",
      difficultyDistribution: { easy: 25, medium: 45, hard: 20, higherOrder: 10 },
      durationMinutes: 30,
      totalMarks: 50,
      questionTypes: "all",
      randomizeQuestions: true,
      randomizeOptions: true,
      includeAnswers: false,
      includeSourceReferences: true,
      useExactBookAnswers: true,
    },
  },
  {
    id: "monthly_exam",
    title: "اختبار الشهر المعتمد (Monthly Exam)",
    description: "اختبار شهري وزاري يغطي وحدة دراسية كاملة أو عدة دروس بتوازن دقيق في جدول المواصفات.",
    iconName: "Calendar",
    badge: "45 دقيقة • 35 سؤالاً",
    config: {
      questionCount: 35,
      examCount: 1,
      difficultyPreset: "balanced",
      difficultyDistribution: { easy: 25, medium: 40, hard: 25, higherOrder: 10 },
      durationMinutes: 45,
      totalMarks: 70,
      questionTypes: "all",
      randomizeQuestions: true,
      randomizeOptions: true,
      includeAnswers: false,
      includeSourceReferences: true,
      useExactBookAnswers: true,
    },
  },
  {
    id: "midterm_exam",
    title: "امتحان منتصف الفصل (Midterm Exam)",
    description: "امتحان رسمي متوازن يغطي الفصول الأولى بنسب مدروسة طبقاً للأوزان النسبية لنواتج التعلم.",
    iconName: "Layers",
    badge: "60 دقيقة • 40 سؤالاً",
    config: {
      questionCount: 40,
      examCount: 2,
      difficultyPreset: "balanced",
      difficultyDistribution: { easy: 20, medium: 45, hard: 25, higherOrder: 10 },
      durationMinutes: 60,
      totalMarks: 80,
      questionTypes: "all",
      randomizeQuestions: true,
      randomizeOptions: true,
      includeAnswers: false,
      includeSourceReferences: true,
      useExactBookAnswers: true,
    },
  },
  {
    id: "final_exam",
    title: "امتحان نهاية الترم الشامل (Final Exam)",
    description: "البوكليت الوزاري النهائي الشامل لكافة فصول ودروس المنهج الـ 14 بدقة مطابقة لمعايير قياس التحصيل.",
    iconName: "Award",
    badge: "90 دقيقة • 50 سؤالاً",
    config: {
      scope: "curriculum",
      questionCount: 50,
      examCount: 3,
      difficultyPreset: "balanced",
      difficultyDistribution: { easy: 20, medium: 45, hard: 25, higherOrder: 10 },
      durationMinutes: 90,
      totalMarks: 100,
      questionTypes: "all",
      randomizeQuestions: true,
      randomizeOptions: true,
      includeAnswers: false,
      includeSourceReferences: true,
      useExactBookAnswers: true,
    },
  },
  {
    id: "revision_bank",
    title: "بنك المراجعة العامة الشامل (Revision Bank)",
    description: "توليد الحد الأقصى المفيد من الأسئلة المتدرجة مع إتاحة الإجابات النموذجية وسلالم التصحيح للمذاكرة.",
    iconName: "Sparkles",
    badge: "الحد الأقصى • أسئلة محلولة",
    config: {
      questionCount: "max",
      examCount: 1,
      difficultyPreset: "balanced",
      difficultyDistribution: { easy: 30, medium: 40, hard: 20, higherOrder: 10 },
      durationMinutes: 120,
      totalMarks: 150,
      questionTypes: "all",
      randomizeQuestions: false,
      randomizeOptions: false,
      includeAnswers: true,
      includeSourceReferences: true,
      useExactBookAnswers: true,
    },
  },
  {
    id: "excellent_student",
    title: "امتحان الطلاب الفائقين والمتفوقين (Olympiad / Honors)",
    description: "تركيز مكثف على مستويات التفكير العليا والتحليل والربط بين الدروس ومواقف حل المشكلات البرمجية والأمنية.",
    iconName: "TrendingUp",
    badge: "60 دقيقة • تركيز تحليلي",
    config: {
      questionCount: 30,
      examCount: 1,
      difficultyPreset: "excellent_student",
      difficultyDistribution: { easy: 10, medium: 25, hard: 45, higherOrder: 20 },
      durationMinutes: 60,
      totalMarks: 60,
      questionTypes: ["compare", "give_reason", "what_if", "odd_one_out", "order", "classify", "essay", "cross_lesson"],
      randomizeQuestions: true,
      randomizeOptions: true,
      includeAnswers: false,
      includeSourceReferences: true,
      useExactBookAnswers: true,
    },
  },
  {
    id: "parallel_models",
    title: "نماذج اختبارية متكافئة (A / B / C Models)",
    description: "توليد عدة نماذج امتحانية مستقلة ومتطابقة في جدول المواصفات والصعوبة وتوزيع الدرجات لتفادي الغش.",
    iconName: "Copy",
    badge: "4 نماذج متكافئة • A, B, C, D",
    config: {
      questionCount: 30,
      examCount: 4,
      difficultyPreset: "balanced",
      difficultyDistribution: { easy: 25, medium: 40, hard: 25, higherOrder: 10 },
      durationMinutes: 60,
      totalMarks: 60,
      questionTypes: "all",
      randomizeQuestions: true,
      randomizeOptions: true,
      includeAnswers: false,
      includeSourceReferences: true,
      useExactBookAnswers: true,
    },
  },
];
